### ISSUE TITLE
下载下来pnpm dev:h5，打开后是空白页面，只有一个标题Starter-Uni，pnpm dev:mp-weixin正常

### ISSUE THREAD

**Issue by lentg** [zguolee/starter-uni#1]

**Comment by nei1ee** [comment]
控制台是否有报错，我这里试了没有问题。

**Comment by lentg** [comment]
import 'uno.css'
问题出在这这行代码，注解了就能打开

**Comment by lentg** [comment]
小程序上没问题

**Comment by nei1ee** [comment]
我重新clone一下，仍然没有复现问题🙉，能否给一个你现在的repo。

**Comment by lentg** [comment]
我两台电脑都无法跑h5，注解了import 'uno.css'，就能跑，也不提示问题，也不输出错误

**Comment by lentg** [comment]
应该是unocss插件的问题，我在Win10/mac 10.13.6/mac 11.6.8,nodejs 16.6/18都试过了，都跑不了H5，注解了import 'uno.css'就可以。

**Comment by nei1ee** [comment]
<img width="1161" alt="image" src="https://user-images.githubusercontent.com/40738594/186856090-c952c98f-5a33-4c36-8159-0e0088f0d309.png">
我的直接clone是这样，真的不知道是什么问题😂。

**Comment by lentg** [comment]
Todesk
lentg邀请您进行远程控制
ToDesk设备代码:903 294 099
临时密码:a8888888
点击链接直接进行远程控制：
https://wechat.todesk.com/invite-page?id=FTHZ23o-mBmDX4u41wVJJ

**Comment by lentg** [comment]
要请你来看看，你远程这电脑

**Comment by lentg** [comment]
wx号 lentxg

**Comment by lentg** [comment]
发现问题了，是浏览器版本问题，尽量用最新的Chrome来测试
