### ISSUE TITLE
.nvue file support

### ISSUE THREAD

**Issue by Siykt** [zguolee/starter-uni#10]
`.nvue` file support

目前不支持`.nvue`文件的类型解析，主要原因应该是在`eslint-vue-preser`上

![like-this](https://user-images.githubusercontent.com/44022526/236407501-f1e317a4-d57f-4e03-af81-6a3ae5c9326e.png)

复现步骤
1. clone项目
2. 修改`tsconfig.json include` 支持`.nvue`文件解析
  `"include": ["src/**/*.ts", "src/**/*.d.ts", "src/**/*.tsx", "src/**/*.vue", "src/**/*.nvue"]`
3. 修改任意`pages`下的`.vue`为`.nvue`即可复现

**Comment by ModyQyW** [comment]
我认为这应该去 `eslint-vue-parser` 提。`.nvue` 并不属于 `vue` 生态内的通用标准，很有可能被驳回支持。

你可以考虑用户侧的 patch，直接修改 `eslint-vue-parser` 的源码来处理，在源码中找到 `".vue"` 并增加 `.nvue` 的判断应该就可以了。
