### ISSUE TITLE
样式兼容性问题？

### ISSUE THREAD

**Issue by chenjz08** [zguolee/starter-uni#3]
UToast组件中的，css属性"inset"貌似在微信小程序不起作用。（真机调试情况下）

我把“inset-0”改为“top-0 right-0 left:0 bottom-0”就能解决问题。

![image](https://user-images.githubusercontent.com/35839751/191441186-18921e54-6e4e-4485-a766-4ec077b2bb93.png)
(如果可以，让我提个pr解决这个问题？)

**Comment by nei1ee** [comment]
谢谢提问。请问不起作用指什么，toast位置不对还是大小是0x0？之前用的就是`top-0 right-0 left-0 bottom-0`，后来改成了`inset-0`。项目还在开发中，组件之后可能会换一种方式来写，欢迎PR🙌。

**Comment by chenjz08** [comment]
用的是安卓机，toast位置是0x0。我现在用我的ipad试了一下，toast位置是居中的。所以可能是安卓机的微信小程序不支持"inset"。
---
我现在很想参与开源项目的开发。什么时候会开放出来共同开发呢？

**Comment by nei1ee** [comment]
> 用的是安卓机，toast位置是0x0。所以可能是安卓机的微信小程序不支持"inset"。

手机系统版本和微信版本时多少呢？

> 我现在很想参与开源项目的开发。什么时候会开放出来共同开发呢？

我不清楚，组件应该会新开一个项目。
如果只是模板，可以自己维护自己需要的模板的，因为这个模板有很多我自己的想法😂。

**Comment by chenjz08** [comment]
手机：MIUI12.5.4
微信：8.0.27

**Comment by nei1ee** [comment]
如果方便请提个PR修复一下🙌

**Comment by chenjiezi** [comment]
top-0 right-0 left-0 bottom-0

**Comment by chenjz08** [comment]
没问题。我想问一下你遇到```top-0 right-0 left-0 bottom-0```不起作用，是在ios上遇到的是吗？

**Comment by nei1ee** [comment]
> 没问题。我想问一下你遇到`top-0 right-0 left-0 bottom-0`不起作用，是在ios上遇到的是吗？

其实没有遇到这个问题，iOS上没有问题，Toast位置也是对的，没有安卓机没办法去测试😂。
