### ISSUE TITLE
小程序切到后台再切回来，点击Notify组件或者Toast组件显示不出来，控制台有报错。

### ISSUE THREAD

**Issue by chenjz08** [zguolee/starter-uni#5]
- 报错信息：
![image](https://user-images.githubusercontent.com/35839751/191885746-2cdaf466-9493-40f2-bf47-6c90c3e83c53.png)

- 导致报错的位置：
在[UBasePage.vue](https://github.com/zguolee/starter-uni/blob/cd6f211aee1ea5ea60aac7e5bd600cd192d68ded/src/components/UnoUI/UBasePage/UBasePage.vue#L20)中，```onHide```生命钩子会触发```pageReset()```。
```
// pageReset()
notifyRef.value = undefined
toastRef.value = undefined
```

**Comment by chenjz08** [comment]
重置```notifyRef```和```toastRef```的目的是什么？

**Comment by nei1ee** [comment]
> 重置`notifyRef`和`toastRef`的目的是什么？

因为所有页面使用一个`pageStore`，为了避免副作用，所以应该做如下修改。

```diff,ts
- onHidden(() => pageReset())
+ onUnmounted(() => pageReset())
```
