### ISSUE TITLE
打包为APP运行后`Unocss`样式不生效

### ISSUE THREAD

**Issue by aboutZZ** [zguolee/starter-uni#8]
## APP页面

<a href="https://smms.app/image/9DmbXoE8GsTqHtK" target="_blank"><img src="https://s2.loli.net/2022/12/01/9DmbXoE8GsTqHtK.jpg" width="240"></a>

## 下面是正常情况下的样式（H5页面）

<a href="https://smms.app/image/orDHAfE5YTnjR6x" target="_blank"><img src="https://s2.loli.net/2022/12/01/orDHAfE5YTnjR6x.png" width="240"></a>

**Comment by nei1ee** [comment]
因为 `unocss.config.ts` 中平台判断有误，应该只有是小程序的时候 `unocss-applet` 才生效。
