### ISSUE TITLE
运行一段时间会杀死进程，开发效率底下

### ISSUE THREAD

**Issue by q807175022** [zguolee/starter-uni#9]
运行 `pnpm run dev:mp-toutiao` 几分钟后会报错：
![image](https://user-images.githubusercontent.com/34495095/223995040-1e99c78a-d2ee-4b54-9c4e-b9e831401bdf.png)

**Comment by nei1ee** [comment]
uniapp官方已有此问题，https://github.com/dcloudio/uni-app/issues/3603 可能只有windows平台才会出现，等待解决。
